### try catch使用场景

try catch的使用,永远放在自己控制范围之内,而不应该防患位置的错误,即知道改出可能出错,可以使用try catch

#### 1. http请求

使用ajax、fetch和axios异步请求库时,请求失败则会抛出一个错误,需要进行异常捕获

```javascript
try{
  const response =await axios.get('/api/data')
}catch(error){
  console.error('error fetching data: ', error)
}
```

#### 2. JSON解析

JSON.parse解析一个无效的字符串抛出错误

```javascript
try{
  const data=JSON.parse(str)
}catch(error){
  console.error('error parsing data: ', error)
}
```

#### 3. 本地存储访问

如果访问了本地禁用的localStorage和sessionStorage,抛出错误

```javascript
try{
  localStorage.getItem('key')
}catch(){
  console.error('falied to access localStorage: ', error)
}
```

#### 4. Promise链

promise链中,只要有一个promise就会使得整个链条返回错误

```javascript
try{
  const result=await new Promise(...).then(...)
}catch(){
  console.error('error: ', error)
}
```

#### 5. 复杂的计算和操作

复杂的计算,可能会导致异常问题,则采用try…catch进行捕获可能的异常

[参考](https://juejin.cn/post/7273433799689584703?from=search-suggest)